apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: A Python App That Displays Time.
  backstage.io/techdocs-ref: dir:.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
