site_name: 'python-app'
site_description: 'Main documentation for Python apps'
repo_url: https://github.com/yashwanthv-oss/python-app/
edit_uri: blob/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.js`
nav:
  - Overview:
      - Getting Started: 'index.md'